### ISSUE TITLE
Graphql?

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [szczepanmasny/vue-crud#6]
Hey.
On VUE there is no admin which can work with graphql api.
Maybe it would be a good decision to add support?

**Comment by szczepanmasny** [comment]
Hi, thank you very much for this suggestion! It forced me to get acquainted with the GraphQL specification and to check if stable backend libraries supporting this language are available.
GraphQL will solve my overfetching problems and reduce the amount of code in my APIs, so I will definitely add GraphQL support to the project.
If Vue CRUD with GraphQL support would be useful for you and you have an idea how to add this support, I will be grateful for contributing to the project.
I'll try to take care of it next week.

**Comment by Pomazan-Bogdan** [comment]
Glad you liked it.
In my opinion, GraphQL is becoming a standard in implementing APIs and for managing data more and more requests.
I recommend first to get acquainted with the project, As the most functional of the implementations of admin panels to GraphQL:
https://github.com/marmelab/react-admin and https://github.com/zifnab87/ra-component-factory

What questions arise immediately when you connect the admin panel to api?
- Users
- Roles
- Access rights
Of course it should take on the API.
Now the project https://github.com/hasura/graphql-engine becomes popular.

It develops very quickly and does not require manual writing of schemas.
I, as a person who can raise this all, but is difficult with programming, there is a problem with the description of react-admin....

Api has this feature:
If you "set" a tool (for example https://insomnia.rest/) on an existing point, then it can read the entire structure and what this point can provide.

My "idea" is to use this feature, the admin interface tool could make the primary configuration:
- Create a list of sections (entities)
- Subtract fields in these entities
- Build the skeleton of the configuration file based on this information
- Give the ability to customize the visibility of fields in different modes: listing, editing, adding
- enable or disable options for the section: import, export, filtering, and so on.

If you take such an implementation, and take the functionality of Hasurа (but optional), where the guys are very responsive, then this product will be Bomb.

**Comment by sneko** [comment]
@szczepanmasny instead of implementing in addition to VueResource, Apollo or another request client, I would rather leave the choice to the developer.

For example in the refreshList function:
```
      Vue.http.get(url).then((response) => {
        const items = response.body
        selectItems = items.map((item) => {
```

I would use:
```
        const items = this.customGetItems();
        selectItems = items.map((item) => {
```

The developer could give the function pointer while creating the Crud component.
